In [1]:
import tensorflow as tf
import keras
import cv2
import numpy as np
import itertools
import os
import seaborn as sns
from sklearn import preprocessing
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive


In [3]:
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
dir=('/content/drive/MyDrive/dataset/train1/')

In [5]:
classes=["happy1","sad1"]

read all the img and convertin them to array

In [6]:
training_data=[]
img_size=224 
def create_training_data():
  for category in classes:
    path=os.path.join(dir,category)
    class_num=classes.index(category)
    for img in os.listdir(path):
      try:
        img_array=cv2.imread(os.path.join(path,img))
        new_array=cv2.resize(img_array,(img_size,img_size))
        training_data.append([new_array, class_num])
      except Exception as e:
        pass 


In [7]:
create_training_data()

In [8]:
print(len(training_data))

3348


In [9]:
temp=np.array(training_data)

<ipython-input-9-357a9f251f7e>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  temp=np.array(training_data)


In [10]:
temp.shape

(3348, 2)

In [11]:
import random
random.shuffle(training_data)

In [12]:
x=[] #feature/data
y=[] #label

for features,label in training_data:
  
  x.append(features)
  y.append(label)

x=np.array(x)
y=np.array(y)

In [13]:
x.shape

(3348, 224, 224, 3)

In [14]:
x=x/255.0

In [16]:
X=x.reshape(3348,3*224*224)

In [17]:
X.shape

(3348, 150528)

In [18]:
y.shape

(3348,)

In [19]:
from sklearn.svm import SVC

In [20]:
svc_model = SVC()

In [21]:
svc_model.fit(X,y)

SVC()

In [22]:
dir1=('/content/drive/MyDrive/dataset/train')

In [23]:
classes1=["H1","S1"]

In [24]:
test_data=[]
img_size=224 
def create_test_data():
  for category in classes1:
    path=os.path.join(dir1,category)
    class_num=classes1.index(category)
    for img in os.listdir(path):
      try:
        img_array=cv2.imread(os.path.join(path,img))
        new_array=cv2.resize(img_array,(img_size,img_size))
        test_data.append([new_array, class_num])
      except Exception as e:
        pass 

In [25]:
create_test_data()

In [26]:
temp1=np.array(test_data)

<ipython-input-26-3bdf79796c9f>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  temp1=np.array(test_data)


In [27]:
temp1.shape

(384, 2)

In [28]:
import random
random.shuffle(test_data)

In [29]:
x1=[] #feature/data
y1=[] #label

for features,label in test_data:
  
  x1.append(features)
  y1.append(label)

x1=np.array(x1)
y1=np.array(y1)

In [30]:
x1.shape

(384, 224, 224, 3)

In [31]:
a=x1.reshape(384,224*224*3)

In [32]:
a=a/255.0

In [33]:
a

array([[0.07058824, 0.07058824, 0.07058824, ..., 0.98039216, 0.98039216,
        0.98039216],
       [0.69019608, 0.69019608, 0.69019608, ..., 0.01960784, 0.01960784,
        0.01960784],
       [0.94117647, 0.94117647, 0.94117647, ..., 0.56862745, 0.56862745,
        0.56862745],
       ...,
       [0.19215686, 0.19215686, 0.19215686, ..., 0.24313725, 0.24313725,
        0.24313725],
       [0.76862745, 0.76862745, 0.76862745, ..., 0.        , 0.        ,
        0.        ],
       [0.01960784, 0.01960784, 0.01960784, ..., 0.21960784, 0.21960784,
        0.21960784]])

In [34]:
predictions = svc_model.predict(a)

In [38]:
predictions

array([1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,

In [35]:
from sklearn.metrics import classification_report,confusion_matrix

In [36]:
print(confusion_matrix(y1,predictions))

[[188  52]
 [ 20 124]]


In [37]:
print(classification_report(y1,predictions))

              precision    recall  f1-score   support

           0       0.90      0.78      0.84       240
           1       0.70      0.86      0.78       144

    accuracy                           0.81       384
   macro avg       0.80      0.82      0.81       384
weighted avg       0.83      0.81      0.82       384

